import './globals.css'
import type { Metadata } from 'next'
import { Merriweather } from 'next/font/google'
import Header from "@/component/Header/page";

const inter = Merriweather({ weight: ['300'], preload: false, subsets: ['latin'], display: 'swap', })

export const metadata: Metadata = {
  title: 'Valentin Kovalenko',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header />
      {children}
      </body>
    </html>
  )
}
